### PR TITLE
Update ruby version

### PR DESCRIPTION
**Pull request by christoshrousis**
Hey, just a pull request to update ruby before i decided to work on other bounties. Im unsure why but my schema file has changed from master... this may either be from ruby version change affecting the already written migration files, or just a random change on my machine..? excuse my lack of understanding.

### CODE REVIEW

**Comment by christoshrousis** [comment]
One of the bounties mentions SEO, so I got started on something minor. One of the Major SEO updates would be recipe markup.

**Comment by dpick** [comment]
Merged, thanks!

**Comment by christoshrousis** [comment]
Hey no problem. I was worried this project died after seeing no updates on assembly for 2 months. I'm still working on some small bits on the project, will keep busting some stuff out :)

**Comment by dpick** [comment]
Awesome!

It's unfortunately kind of dead at this point. I've had some stuff come up
and haven't had much time to put into it :(. I'm happy to pull stuff in and
deploy though!

**Comment by christoshrousis** [comment]
No problem, I'll happily keep working on it then. Hopefully I can revive the project for you.

**Pull request merged**
